### PR TITLE
Bind DN

### PR DESCRIPTION
**Pull request by nzlosh**
This patch allows the possibility of doing the following:
 1. Binding against the LDAP server with a DN different from the username. (simple bind/anonymous bind)
 2. Authenticate username against a different branch in the directory tree from the bind DN.
 3. Optionally verify the username is a member of a particular group.

### CODE REVIEW

**Comment by Kami** [comment]
Nice, thanks we will review it shortly.

On a related note - can you please update existing tests and add new ones?

**Comment by nzlosh** [comment]
There weren't any existing tests, I'll see what I can produce and create another pull request.

**Comment by nzlosh** [comment]
I've got unit tests in place, it covers:

- anonymous bind
- bind username password
- search username & validate password
- search username, validate password and confirm group membership.

**Comment by semantic-lee** [comment]
can someone at stackstorm merge this pull request 😄

**Comment by lakshmi-kannan** [comment]
LGTM. Merging! Awesome work @nzlosh!

**Pull request merged**
